/**
 * Supabaseクライアント設定
 */

import { createClient } from '@supabase/supabase-js'

// Read from runtime configuration (generated by entrypoint.sh)
// Falls back to import.meta.env for development (Vite dev server)
const getConfig = () => {
  // Runtime config (production) - injected by entrypoint.sh
  if (typeof window !== 'undefined' && (window as any).config) {
    return (window as any).config
  }
  // Build-time config (development) - Vite dev server
  return {
    VITE_SUPABASE_URL: import.meta.env.VITE_SUPABASE_URL,
    VITE_SUPABASE_ANON_KEY: import.meta.env.VITE_SUPABASE_ANON_KEY,
  }
}

const config = getConfig()
const supabaseUrl = config.VITE_SUPABASE_URL
const supabaseAnonKey = config.VITE_SUPABASE_ANON_KEY

// Only create client if env vars are available (for tests, we mock it)
export const supabase = (supabaseUrl && supabaseAnonKey)
  ? createClient(supabaseUrl, supabaseAnonKey)
  : null
