/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly VITE_SUPABASE_URL: string
  readonly VITE_SUPABASE_ANON_KEY: string
  readonly VITE_API_URL?: string
  readonly VITE_E2E_TEST_MODE?: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}

// Runtime configuration (generated by entrypoint.sh at container startup)
interface WindowConfig {
  VITE_SUPABASE_URL: string
  VITE_SUPABASE_ANON_KEY: string
  VITE_BACKEND_URL: string
}

declare global {
  interface Window {
    config?: WindowConfig
  }
}

declare module '*.css' {
  const content: { [className: string]: string }
  export default content
}
